### ISSUE TITLE
Stuck on "cd middleware"

### ISSUE THREAD

**Issue by michaelvorst** [rhodesman/teslaPowerDash#1]
Instructions worked up to the Node JS install.  

You link off to the NodeJS main site, but the installation options are either to download a x64 binary (no idea what to do with this once downloaded), or to install from a package manager, which I did and verified both node and npm were installed. 

No middleware directory could be found after this, so the remaining steps return errors with regard to missing files if I execute them.

Other comments in the install steps: I had to sidestep a bit to install curl, it's not included in Ubuntu by default, might want to mention that - https://www.luminanetworks.com/docs-lsc-610/Topics/SDN_Controller_Software_Installation_Guide/Appendix/Installing_cURL_for_Ubuntu_1.html, and Telegraf was not listed as a package available, so I added it here https://computingforgeeks.com/how-to-install-and-configure-telegraf-on-ubuntu-18-04-debian-9/).

**Comment by rhodesman** [comment]
Ooh man, I think I forgot the whole part where you need to clone the github repo to your machine!  Do all the nodejs  steps from inside the folder of the cloned repository. Sorry about that, I’ll add that to the instructions

**Comment by rhodesman** [comment]
I added the missing steps to the readme.md file
