### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by RAS101389** [rhodesman/teslaPowerDash#2]
I get all the way through "npm start" and the command throws out the below message.

> PWDashboard@1.0.0 start /etc/teslaPowerDash/middleware
> nodemon app.js

>[nodemon] 1.18.10
>[nodemon] to restart at any time, enter `rs`
>[nodemon] watching: *.*
>[nodemon] starting `node app.js`
>Server running at http://192.168.1.185:3301
>/etc/teslaPowerDash/middleware/api/controllers/appController.js:7
>  if (err) throw err;
> _______^

>Error: ENOENT: no such file or directory, open 'setup/pwSettings.json'
>[nodemon] app crashed - waiting for file changes before starting...

I have edited the "appController.js" file and have been able to get to the web page but hitting the save button does not do anything at that point.

**Comment by rhodesman** [comment]
fixed issue with latest push.  Update with a new pull and give that a try
