### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by natrlhy** [rhodesman/teslaPowerDash#20]
Hi!

Is there a way to import the historical data from the time Tesla solar and Powerwalls were installed?

Thanks!

**Comment by rhodesman** [comment]
you can export the data via the Tesla app to CSV files.  Then you can import those CSV files to a database of your choosing.  I did this with MySQL running on the grafana server and connected grafana to that DB and use that when I need to see data previous to a date I had the influxdb capturing data.

**Comment by natrlhy** [comment]
Thanks. I may try that. I've been using the container approach and mentioned by #3 and I lost my 5 days of data. Have you encountered a way to export/save the influxdb data?

**Comment by rhodesman** [comment]
@natrlhy I have not tried to export data from influxDB but I am sure it's possible.  However, it's currently out of scope for this application at this time.
