### ISSUE TITLE
Can not seem to get the oAuth Token process to work

### ISSUE THREAD

**Issue by ssossam** [rhodesman/teslaPowerDash#24]
You mention Telsa id and password.  Is this to the Powerwall or to my Telsa account at Tesla.com ?

Not getting desired results to fire up the dashboard.

Thanks for any assistance

**Comment by rhodesman** [comment]
@ssossam I had to make edits to the code to work with the new Tesla Authentication protocols.  Please update your code and see documentation for further assistance.
