### ISSUE TITLE
telegraf causing inverter to lock up?

### ISSUE THREAD

**Issue by Landmine-1252** [rhodesman/teslaPowerDash#25]
I've noticed since running telegraf to capture data via the API my follower inverter stops working. If I stop telegraf within 5 minutes the inverter starts working again. I'm running 2 Powerwall+ batteries on firmware 21.20.2-RC4 with PTO currently. My system is not pulling from my batteries but solar and inverters are providing power to my home.

I could very well be wrong, but thought I'd share that here and see if a good conversation could be had.

**Comment by rhodesman** [comment]
I have not heard or experienced this issue.  Have you tried to call Tesla and see if they can look at the inverter logs and see if the dashboard is indeed causing the lockup?  See if they can send you and log information and that way I'll be better capable of diagnosing the issue.

Thanks!

P.s. sorry for the long response time, been a busy summer thus far.

**Comment by Landmine-1252** [comment]
They are having all kinds of other issues with my Powerwall+ setup so I'll wait until it just base line works before trying to push for anything that isnt out of the box. Thank you!
