### ISSUE TITLE
Add Dockerfile build?

### ISSUE THREAD

**Issue by liveaverage** [rhodesman/teslaPowerDash#3]
First and foremost, **outstanding** work on putting this together! While I haven't tweaked all dashboard settings yet, your documentation, details, and configurations were **immensely** helpful! Not sure if you're interested, but I took a containerized approach based on your work (and credited you + the project) to establish an all-in-one dashboard solution. There are some notable differences:

- Use of centos:7 as the base image
- No middleware component -- I exclusively wanted data provided locally by the Powerwall 2 Backup Gateway
- Use of provisioners to bootstrap Grafana datasources/dashboards

That said, I can fork and submit a PR to merge a supplemental dockerbuild directory with all necessary artifacts if you'd like to include it in your source repo: https://github.com/liveaverage/docker-powerwall-dashboard

Really just wanted to thank you for publishing/sharing this! Great work!

**Comment by rhodesman** [comment]
Awesome!! Glad to see you building into docker!!  I would not be apposed to a fork and merge for a dockerbuild solution.  Feel free, I would love to give this project more avenues for people to build/use.  

There are a few items that the Tesla API gives you that I struggled to find in the local gateway API but I'm sure they are there somewhere, I just need to spend some more time poking around with it.

Thanks again for the kudos, happy to help where I can.  Definitely one of the more fun projects I've done in a while.

**Comment by natrlhy** [comment]
I'm leveraging the container approach, too. Testing it out on Windows Docker currently and working well!
