### ISSUE TITLE
Stuck on the Middleware section

### ISSUE THREAD

**Issue by shanep2300** [rhodesman/teslaPowerDash#4]
I'm getting all of these errors:

![2019-07-28_14-41-08](https://user-images.githubusercontent.com/16820289/62011383-c5bf0200-b145-11e9-90b9-4b4bb1235e8e.png)

Every other step before this, worked flawlessly though! Thank you!!!

**Comment by rhodesman** [comment]
Seeing that you're doing this on a raspberry pi, it might be missing some prerequisits that libcurl needs to even be installed.  In that case do this first:  
`sudo apt-get install python libcurl4-openssl-dev build-essential`

Then try installing libcurl with root permissions:
`sudo npm install node-libcurl --build-from-source --curl_static_build=true --save`

Let me know if that works.

**Comment by shanep2300** [comment]
Ok, part of the issue was on my end... Still got lots of errors but I had to access the link from the Pi itself, not my computer. Got the site up and running. Added everything but Tesla ID and Secret, clicked saved, and no keys were generated.

**Comment by rhodesman** [comment]
Yes, the system not generating a key is a known issue.  I'm working on a fix that will automatie that whole process.  Still in flight, but for the time being you can pull the api data directly from the powerwall gateway API

**Comment by Nakatomi2010** [comment]
Try installing NodeJS 11.10 using:  sudo npm install node-libcurl --build-from-source --curl_static_build=true --save --unsafe-perm


You'll need to uninstall NodeJS 12 first though.
