### ISSUE TITLE
Weather info stuck in N/A

### ISSUE THREAD

**Issue by shanep2300** [rhodesman/teslaPowerDash#5]
I know this is a third party api, but when I get the site with my lat/lon it works fine. Grafana doesn't want to display anything though and the queries are set up correctly.

**Comment by liveaverage** [comment]
@shanep2300  Just wanted to mention that the telegraf input for weather wasn't defined in the repo's configuration. I had to manually add this, but it worked fine once present.: https://github.com/liveaverage/docker-powerwall-dashboard/blob/master/powerwall.conf#L16-L26

Note: I provided a name override of "weather" to make the query reference more universal when reusing the grafana dashboard: https://github.com/liveaverage/docker-powerwall-dashboard/blob/master/graf_dash.json#L730-L733

**Comment by rhodesman** [comment]
Thank you @liveaverage !!

**Comment by shanep2300** [comment]
@liveaverage That worked perfectly!! How do you use the "weather" name in Grafana (new to Grafana :))?

Lastly, do you know how to change the temp to F? I'm guessing I would have to add a math eq to get it working properly?

**Comment by liveaverage** [comment]
The second link (https://github.com/liveaverage/docker-powerwall-dashboard/blob/master/graf_dash.json#L730-L733) shows the raw query in an exported grafana dashboard referencing the `weather` table, along with the conversion to Fahrenheit -- I had the same preference :) I store the values as Celsius and render as Fahrenheit with the grafana query. You can manipulate via GUI, too, by clicking the weather "panel" and selecting "Edit": https://imgur.com/a/AUPBYLQ

**Comment by shanep2300** [comment]
Awesome! Thank you very much for the help!
